"""Actualizando modelo Vehicle

Revision ID: 0b46f409885a
Revises: 
Create Date: 2025-09-08 12:38:53.287044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b46f409885a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_brand', sa.String(length=100), nullable=False),
    sa.Column('arrival_location', sa.String(length=100), nullable=False),
    sa.Column('applicant', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
